# vim: filetype=sh

startif() {
	pgrep "$1" >/dev/null || "$@" >/dev/null 2>&1 &
}

"$HOME"/.local/bin/scrmain
"$HOME"/.local/bin/kb
startif dunst
startif compton
pgrep musicpd >/dev/null || musicpd >/dev/null 2>&1
startif mpd-notification
startif lowbat
startif emacs --daemon
notify-send -u low -t 2000 'emacs' '  Emacs daemonized'
cd "$HOME"
xrdb "$HOME"/.config/x11/xresources
notify-send -u normal 'Welcome' "  Welcome back, partner\!"
exec dwm
