# vim: filetype=sh

startif() {
	pgrep "$1" >/dev/null || "$@" >/dev/null 2>&1 &
}

export LANG='en_US.UTF-8'
pgrep musicpd >/dev/null || musicpd >/dev/null 2>&1
"$HOME"/.local/bin/setwp
"$HOME"/.local/bin/kb
xset s off
xset -dpms
startif dunst
startif picom
startif lowbat
startif mpd-notification
startif xscreensaver --no-splash
startif dwmblocks
# ekb
cd "$HOME"
xrdb "$HOME"/.config/x11/xresources
notify-send -u normal 'Welcome' "  Welcome back, partner\!"
dbus-launch dwm
