wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [50, 50, 50, 50, 90]
    rows: [8, 10, 12, 3, 4, 90]
  refreshInterval: 1
  mods:
    digitalclock:
      color: orange
      enabled: true
      font: digitalfont
      hourFormat: 24
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 1
      title: "big clock"
      type: "digitalclock"
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    feedreader:
      enabled: true
      feeds:
      - http://feeds.bbci.co.uk/news/rss.xml
      feedLimit: 10
      position:
        top: 2
        left: 0
        width: 2
        height: 1
      refreshInterval: 900
    hackernews:
      enabled: true
      numberOfStories: 10
      position:
        top: 2
        left: 2
        width: 2
        height: 1
      storyType: top
      refreshInterval: 900
    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 0
        left: 0
        height: 2
        width: 1
      refreshInterval: 1
      showCPU: true
      showMem: true
      showSwp: true
