# Audio files to be played. There can be several, in that case
# only the first one is being played unless the 'random' option
# is set to 'true'
files = [
	'dl/Songs Of Anarchy/2011 Songs of Anarchy：Music From Sons of Anarchy Seasons 1-4 (US, 88691 91432 2)/09 Paul Brady & The Forest Rangers - Gimme Shelter.flac',
#	'/usr/home/jozan/mu/ost/mick_gordon/2020_doom_eternal_original_game_soundtrack/02_cultist_base.flac',
#	'/usr/home/jozan/mu/progressive/progressive_black_metal/deathspell_omega/2010_paracletus/02_wings_of_predation.flac',
#	'/usr/home/jozan/mu/metal/technical_death_metal/gojira/2016_magma/04_stranded.flac',
#	'/usr/home/jozan/mu/metal/technical_death_metal/gojira/2005_form_mars_to_sirius/02_backbone.flac',
#	'/usr/home/jozan/mu/metal/technical_death_metal/ulcerate/2011_the_destroyers_of_all/07_the_destroyers_of_all.flac',
#	'/usr/home/jozan/mu/rock/grunge/nirvana/2009_bleach_20th_anniversary_deluxe_edition/04_school.flac',
]
# The program used to play the music files
# Default: 'mpv'
media_player = 'mpv'
# Command-line options to be passed to the program
# Default: [ '--no-video', '--loop' ]
player_options = [
	'--no-video',
	'--loop',
]
# Choose a random audio file in the list
# Default: false
random = true
# Display a cool fortune message
# Default: true
fortune = true
