# Audio files to be played. There can be several, in that case
# only the first one is being played unless the 'random' option
# is set to 'true'
files = [
	# '/home/jozan/mu/rock/grunge/alice_in_chains/1992_dirt/01_them_bones.flac',
	# '/home/jozan/mu/rock/stoner_rock/slo_burn/1997_amusing_the_amazing_ep/03_pilot_the_dune.flac'
	# '/usr/local/hdd/jozan/dl/Songs Of Anarchy/2015 Songs of Anarchy：Vol. 4 (US, 88875 06146 2)/05 Billy Valentine & The Forest Rangers - All Along The Watchtower.flac',
	# 'dl/Songs Of Anarchy/2011 Songs of Anarchy：Music From Sons of Anarchy Seasons 1-4 (US, 88691 91432 2)/09 Paul Brady & The Forest Rangers - Gimme Shelter.flac',
	'/home/jozan/mu/ost/mick_gordon/2020_doom_eternal_original_game_soundtrack/02_cultist_base.flac',
	# '/home/jozan/mu/progressive/progressive_black_metal/deathspell_omega/2010_paracletus/02_wings_of_predation.flac',
#	'/home/jozan/mu/metal/technical_death_metal/gojira/2016_magma/04_stranded.flac',
	# '/home/jozan/mu/metal/technical_death_metal/gojira/2005_form_mars_to_sirius/02_backbone.flac',
#	'/usr/home/jozan/mu/metal/technical_death_metal/ulcerate/2011_the_destroyers_of_all/07_the_destroyers_of_all.flac',
#	'/home/jozan/mu/rock/grunge/nirvana/2011_nevermind_20th_anniversary_deluxe_edition/cd_1/04_breed.flac',
	# '/home/jozan/mu/rock/grunge/alice_in_chains/1990_facelift/02_man_in_the_box.flac',
#	'/var/hdd/files/mu/rock/grunge/alice_in_chains/1992_dirt/11_angry_chair.flac',
#	'/var/hdd/files/mu/rock/grunge/soundgarden/1994_superunknown/04_mailman.flac',
	# '/var/hdd/files/mu/rock/grunge/nirvana/2005_sliver_the_best_of_the_box_compilation/03_mrs._butterworth_rehearsal_demo.flac',
	# '/home/jozan/mu/rock/grunge/nirvana/2009_bleach_20th_anniversary_deluxe_edition/04_school.flac',
]
# The program used to play the music files
# Default: 'mpv'
media_player = 'mpv'
# Command-line options to be passed to the program
# Default: [ '--no-video', '--loop' ]
player_options = [
	'--no-video',
	'--loop',
]
# Choose a random audio file in the list
# Default: false
random = true
# Display a cool fortune message
# Default: true
fortune = true
